spring:
  data:
    mongodb:
      uri: mongodb+srv://mongoadmin:April863$$@boutiqueproducts.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
      database: products
      username: mongoadmin
      password: April863$$
      authentication-database: mongoadmin