apiVersion: apps/v1
kind: Deployment
metadata:
  name: new
  labels:
    app: new
  namespace: namespace-workflow-1710761403679
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new
  template:
    metadata:
      labels:
        app: new
    spec:
      containers:
        - name: new
          image: acrworkflow1710761403679.azurecr.io/image-workflow-1710761403679:latest
          ports:
            - containerPort: 8080