apiVersion: apps/v1
kind: Deployment
metadata:
  name: prachiboutique
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prachiboutique
  template:
    metadata:
      labels:
        app: prachiboutique
    spec:
      containers:
      - name: boutique-container
        image: boutique.azurecr.io/boutiquefinal:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth-boutique  # Name of the Docker registry secret