apiVersion: apps/v1
kind: Deployment
metadata:
  name: prachi-boutique
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prachi-boutique
  template:
    metadata:
      labels:
        app: prachi-boutique
    spec:
      containers:
      - name: boutique-container
        image: boutique.azurecr.io/boutiquefinal:v1
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: acr-auth-boutique
