apiVersion: apps/v1
kind: Deployment
metadata:
  name: boutique
spec:
  replicas: 3
  selector:
    matchLabels:
      app: boutique
  template:
    metadata:
      labels:
        app: boutique
    spec:
      containers:
      - name: boutique-container
        image: boutique.azurecr.io/boutiquefinal:v1
        ports:
        - containerPort: 90
      imagePullSecrets:
      - name: acr-auth1  # Name of the Docker registry secret