apiVersion: apps/v1
kind: Deployment
metadata:
  name: prachi-boutique
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prachi-boutique
  template:
    metadata:
      labels:
        app: prachi-boutique
    spec:
      containers:
      - name: boutique-container
        image: nginx:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth-boutique
