apiVersion: v1
kind: Service
metadata:
  name: prachi-boutique
spec:
  selector:
    app: prachi-boutique
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
