apiVersion: v1
kind: Service
metadata:
  name: boutique-service
spec:
  selector:
    app: prachiboutique
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Assuming your application runs on port 8080
