apiVersion: v1
kind: Service
metadata:
  name: new
  namespace: namespace-workflow-1710761403679
spec:
  type: LoadBalancer
  selector:
    app: new
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080